module.exports = {
  path: "/test/walk",
  headers: {
    Accept: "application/json",
    "Accept-Language": "en-US,en;q=0.8",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "US",
    Host: "foobar.execute-api.us-east-1.amazonaws.com",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0",
    Via: "1.1 foobar.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "foobar",
    "X-Forwarded-For": "127.0.0.1",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https",
  },
  pathParameters: {
    proxy: "hello",
  },
  requestContext: {
    accountId: "f-oobar",
    resourceId: "fooba-r",
    stage: "test",
    requestId: "5a2186ea-9a36-11eb-b982-671cc1ab0788",
    identity: {
      cognitoIdentityPoolId: "",
      accountId: "",
      cognitoIdentityId: "",
      caller: "",
      apiKey: "",
      sourceIp: "127.0.0.1",
      cognitoAuthenticationType: "",
      cognitoAuthenticationProvider: "",
      userArn: "",
      userAgent: "Mozilla/5.0",
      user: "",
    },
    resourcePath: "/{proxy+}",
    httpMethod: "POST",
    apiId: "foobar",
  },
  resource: "/{proxy+}",
  httpMethod: "POST",
  body: '{"url":"http://localhost:8888/","method":"GET","timeout":"60000"}',
  queryStringParameters: {
    foo: "bar",
  },
  stageVariables: {
    foo: "bar",
  },
};
